# Generated by Django 5.0.14 on 2026-01-27 22:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('F', 'Women'), ('CHILD', 'Children')], help_text='Gender category this staff can manage (null = all)', max_length=10, null=True),
        ),
    ]
