# Generated by Django 5.0.14 on 2026-01-27 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_allowed_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly salary for staff members', max_digits=10),
        ),
        migrations.CreateModel(
            name='StaffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date payment was made')),
                ('period_month', models.IntegerField(help_text='Month this payment covers (1-12)')),
                ('period_year', models.IntegerField(help_text='Year this payment covers')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHECK', 'Check')], default='CASH', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='Admin who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_payments', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Payment',
                'verbose_name_plural': 'Staff Payments',
                'db_table': 'staff_payments',
                'ordering': ['-payment_date', '-created_at'],
                'unique_together': {('staff', 'period_month', 'period_year')},
            },
        ),
    ]
