# Generated by Django 5.0.14 on 2026-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_monthly_salary_staffpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the user was archived', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived users are hidden but not deleted'),
        ),
    ]
