# Generated by Django 4.2.27 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_archived_at_user_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_gender',
            field=models.CharField(blank=True, help_text='Gender categories this staff can manage, comma-separated (e.g. "M,F" or "CHILD"). Null = all.', max_length=20, null=True),
        ),
    ]
