# Generated by Django 5.0.14 on 2026-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_allow_multi_gender_in_allowed_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes_taught',
            field=models.CharField(blank=True, help_text='Classes/grades taught (for school teachers)', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, help_text='Teaching qualification (for school teachers)', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject taught (for school teachers)', max_length=100),
        ),
    ]
