# Generated by Django 4.2.27 on 2026-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial (14 days)'), ('basic', 'Basic - 200 DH/mo'), ('pro', 'Pro - 500 DH/mo'), ('enterprise', 'Enterprise - Custom')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20),
        ),
    ]
