# Generated by Django 5.0.14 on 2026-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='business_type',
            field=models.CharField(choices=[('gym', 'Gym'), ('school', 'School')], default='gym', help_text='Type of business: gym or school', max_length=10),
        ),
        migrations.AlterField(
            model_name='gym',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Trial (14 days)'), ('pro', 'Pro - 200 DH/month'), ('lifetime', 'Lifetime - 2000 DH')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='gym',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=20),
        ),
    ]
