# Generated by Django 5.0.14 on 2026-01-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('members', '0002_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(help_text='Staff member who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(help_text='Member who made the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='membership_plan',
            field=models.ForeignKey(help_text='Plan paid for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gym.membershipplan'),
        ),
    ]
