# Generated by Django 5.0.14 on 2026-02-21 21:14

import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(default=licenses.models.generate_license_key, help_text='Auto-generated license key (MOL-XXXX-XXXX-XXXX)', max_length=20, unique=True)),
                ('tier', models.CharField(choices=[('trial', 'Trial (14 days)'), ('monthly', 'Monthly (30 days)'), ('yearly', 'Yearly (365 days)'), ('lifetime', 'Lifetime')], default='yearly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('gym_name', models.CharField(blank=True, default='', max_length=200)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('owner_phone', models.CharField(blank=True, default='', max_length=30)),
                ('max_members', models.IntegerField(default=500)),
                ('device_id', models.CharField(blank=True, help_text='Bound device identifier (set on first activation)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires (lifetime)', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
