# Generated by Django 4.2.27 on 2026-02-04 20:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='color',
            field=models.CharField(blank=True, default='#2196F3', help_text='Hex color for UI display', max_length=20),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='icon',
            field=models.CharField(blank=True, default='fitness_center', help_text='Material icon name for UI display', max_length=50),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of name', max_length=100),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='name_fr',
            field=models.CharField(blank=True, help_text='French translation of name', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='age_category',
            field=models.CharField(choices=[('adult', 'Adults Only'), ('kids', 'Kids Only'), ('any', 'Any Age')], default='any', help_text='Age restriction for this plan', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_gender',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'Any Gender')], default='any', help_text='Gender restriction for this plan', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='currency',
            field=models.CharField(default='MAD', help_text='Currency code (MAD, EUR, USD)', max_length=5),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='insurance_required',
            field=models.BooleanField(default=False, help_text='Whether insurance payment is required for check-in'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of name', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='name_fr',
            field=models.CharField(blank=True, help_text='French translation of name', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='sessions_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum sessions allowed (null = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
