# Generated by Django 4.2.27 on 2026-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_activitytype_color_activitytype_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Activity Type', 'verbose_name_plural': 'Activity Types'},
        ),
        migrations.AddField(
            model_name='activitytype',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order for UI sorting (lower = first)'),
        ),
    ]
