# Generated by Django 5.0.14 on 2026-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_add_order_to_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Subject weight/coefficient for grading (1-10). Used by schools.'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=0, help_text='Weekly hours for this subject. Used by schools.'),
        ),
    ]
