# Generated by Django 5.0.14 on 2026-01-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(help_text='Phone number (parent phone for kids)', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('subscription_start', models.DateField(blank=True, help_text='Start date of current subscription', null=True)),
                ('subscription_end', models.DateField(blank=True, help_text='End date of current subscription (calculated on payment)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the member')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the member account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(help_text='Activity type the member is enrolled in', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='gym.activitytype')),
                ('membership_plan', models.ForeignKey(help_text='Current membership plan', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='gym.membershipplan')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['-created_at'],
            },
        ),
    ]
