# Generated by Django 5.0.14 on 2026-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age_category',
            field=models.CharField(blank=True, choices=[('ADULT', 'Adult'), ('CHILD', 'Child')], help_text='Age category: Adult or Child', max_length=10),
        ),
    ]
