# Generated by Django 5.0.14 on 2026-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the member was archived', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived members are hidden but not deleted'),
        ),
    ]
