# Generated by Django 5.0.14 on 2026-01-31 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_archived_at_member_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER_3_DAYS', '3-Day Reminder'), ('EXPIRED_UNPAID', 'Expired Unpaid')], max_length=20)),
                ('subscription_end_date', models.DateField(help_text='The subscription end date this notification refers to')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='members.member')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['member', 'notification_type', 'subscription_end_date'], name='notificatio_member__4f5e2c_idx')],
            },
        ),
    ]
