# Generated by Django 4.2.27 on 2026-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for current subscription', max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='cin',
            field=models.CharField(blank=True, help_text='National Identity Card', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='insurance_paid',
            field=models.BooleanField(default=False, help_text='Has paid yearly insurance'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_code',
            field=models.CharField(blank=True, help_text='Gym Member ID (scan/entry)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/'),
        ),
    ]
