# Generated by Django 4.2.27 on 2026-02-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_amount_paid_member_cin_member_insurance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='Place of Birth', max_length=100),
        ),
    ]
