# Generated by Django 4.2.27 on 2026-02-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='insurance_year',
            field=models.CharField(blank=True, help_text='Year of insurance payment', max_length=4),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=20),
        ),
    ]
