# Generated by Django 5.0.14 on 2026-02-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_insurance_year_member_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade/class level (for school students)', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent/guardian email', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_name',
            field=models.CharField(blank=True, help_text='Parent/guardian name', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent/guardian phone', max_length=20),
        ),
    ]
