# Generated by Django 5.0.14 on 2026-01-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(help_text='Member who checked in', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member'),
        ),
    ]
