# Generated by Django 4.2.27 on 2026-02-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='activity_at_entry',
            field=models.ForeignKey(blank=True, help_text='Activity type at time of check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='gym.activitytype'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkin_reason',
            field=models.CharField(blank=True, help_text='Reason for check-in result (ok, debt, insurance, expired)', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkin_result',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('warning', 'Warning'), ('blocked', 'Blocked')], default='allowed', help_text='Decision engine result', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='debt_at_entry',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Member debt at time of check-in', max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='insurance_paid_at_entry',
            field=models.BooleanField(default=False, help_text='Insurance status at time of check-in'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for override (required if override_used=True)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='override_used',
            field=models.BooleanField(default=False, help_text='Whether admin override was used'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_at_entry',
            field=models.CharField(blank=True, help_text='Member status at check-in (ACTIVE/EXPIRED/PENDING)', max_length=20),
        ),
    ]
