# Generated by Django 4.2.27 on 2026-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_activity_at_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('qr', 'QR Code Scan'), ('staff', 'Staff Entry')], default='staff', help_text='How the check-in was performed', max_length=10),
        ),
    ]
